# Generated by Django 3.0.5 on 2020-09-04 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título da Notícia')),
                ('texto', models.TextField(verbose_name='Texto da Notícia')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Autor')),
            ],
        ),
    ]
